### ISSUE TITLE
Паблик в вк по нетсталкингу 

### ISSUE THREAD

**Issue by VolkovsosipisosSnovaISnova** [netstalking-core/netstalking-catalogue#16]
Добро пожаловать в центральное
сообщество по нетсталкингу. Мы всегда рады каждому вступающему и с радостью ответим на любые ваши вопросы в конференции сообщества или личных сообщениях, если вы не жалуете беседы.

Будьте осторожны при просмотре неприятного контента, если же вы слабонервны или легко внушаемы. Администрация проекта не примет на себя ответственность за любой причиненный вам вред, однако следует помнить, что ни один файл или объект не может негативным образом повлиять на ваше самочувствие в силу особенностей человеческого восприятия поступающей информации, и поэтому единственным вашим врагом остаетесь вы сами и сила вашего самовнушения.

vk.com/darksearch

![1596002718](https://user-images.githubusercontent.com/68951345/88793548-0369c700-d1ae-11ea-81cd-ee0d83929bb6.jpg)

P.s: волков, ты можешь удалять сколько угодно. Каждый раз мне тут же приходит уведомление)))

**Comment by ASFH** [comment]
Какой Волков, шизоид. Ваш паблик и так давно в списке каталога, открой глаза и посмотри блядь. Хватит срать сюда.
